/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface FrontendLibInterface extends utils.Interface {
  contractName: "FrontendLib";
  functions: {
    "getHydraS1AccountboundAttesterDestinationOfNullifierBatch(uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getHydraS1AccountboundAttesterDestinationOfNullifierBatch",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHydraS1AccountboundAttesterDestinationOfNullifierBatch",
    data: BytesLike
  ): Result;

  events: {};
}

export interface FrontendLib extends BaseContract {
  contractName: "FrontendLib";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FrontendLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getHydraS1AccountboundAttesterDestinationOfNullifierBatch(
      nullifiers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  getHydraS1AccountboundAttesterDestinationOfNullifierBatch(
    nullifiers: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<string[]>;

  callStatic: {
    getHydraS1AccountboundAttesterDestinationOfNullifierBatch(
      nullifiers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    getHydraS1AccountboundAttesterDestinationOfNullifierBatch(
      nullifiers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHydraS1AccountboundAttesterDestinationOfNullifierBatch(
      nullifiers: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
