/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type AttestationStruct = {
  collectionId: BigNumberish;
  owner: string;
  issuer: string;
  value: BigNumberish;
  timestamp: BigNumberish;
  extraData: BytesLike;
};

export type AttestationStructOutput = [
  BigNumber,
  string,
  string,
  BigNumber,
  number,
  string
] & {
  collectionId: BigNumber;
  owner: string;
  issuer: string;
  value: BigNumber;
  timestamp: number;
  extraData: string;
};

export type ClaimStruct = {
  groupId: BigNumberish;
  claimedValue: BigNumberish;
  extraData: BytesLike;
};

export type ClaimStructOutput = [BigNumber, BigNumber, string] & {
  groupId: BigNumber;
  claimedValue: BigNumber;
  extraData: string;
};

export type RequestStruct = { claims: ClaimStruct[]; destination: string };

export type RequestStructOutput = [ClaimStructOutput[], string] & {
  claims: ClaimStructOutput[];
  destination: string;
};

export interface HydraS1SimpleAttesterInterface extends utils.Interface {
  contractName: "HydraS1SimpleAttester";
  functions: {
    "AUTHORIZED_COLLECTION_ID_FIRST()": FunctionFragment;
    "AUTHORIZED_COLLECTION_ID_LAST()": FunctionFragment;
    "buildAttestations(((uint256,uint256,bytes)[],address),bytes)": FunctionFragment;
    "deleteAttestations(uint256[],address,bytes)": FunctionFragment;
    "generateAttestations(((uint256,uint256,bytes)[],address),bytes)": FunctionFragment;
    "getAttestationRegistry()": FunctionFragment;
    "getAvailableRootsRegistry()": FunctionFragment;
    "getCommitmentMapperRegistry()": FunctionFragment;
    "getDestinationOfNullifier(uint256)": FunctionFragment;
    "getNullifierFromExtraData(bytes)": FunctionFragment;
    "getVerifier()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "AUTHORIZED_COLLECTION_ID_FIRST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUTHORIZED_COLLECTION_ID_LAST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buildAttestations",
    values: [RequestStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAttestations",
    values: [BigNumberish[], string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateAttestations",
    values: [RequestStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRootsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentMapperRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDestinationOfNullifier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNullifierFromExtraData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTHORIZED_COLLECTION_ID_FIRST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUTHORIZED_COLLECTION_ID_LAST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRootsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentMapperRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDestinationOfNullifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNullifierFromExtraData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;

  events: {
    "AttestationDeleted(tuple)": EventFragment;
    "AttestationGenerated(tuple)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NullifierDestinationUpdated(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AttestationDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AttestationGenerated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NullifierDestinationUpdated"
  ): EventFragment;
}

export type AttestationDeletedEvent = TypedEvent<
  [AttestationStructOutput],
  { attestation: AttestationStructOutput }
>;

export type AttestationDeletedEventFilter =
  TypedEventFilter<AttestationDeletedEvent>;

export type AttestationGeneratedEvent = TypedEvent<
  [AttestationStructOutput],
  { attestation: AttestationStructOutput }
>;

export type AttestationGeneratedEventFilter =
  TypedEventFilter<AttestationGeneratedEvent>;

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type NullifierDestinationUpdatedEvent = TypedEvent<
  [BigNumber, string],
  { nullifier: BigNumber; newOwner: string }
>;

export type NullifierDestinationUpdatedEventFilter =
  TypedEventFilter<NullifierDestinationUpdatedEvent>;

export interface HydraS1SimpleAttester extends BaseContract {
  contractName: "HydraS1SimpleAttester";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HydraS1SimpleAttesterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    AUTHORIZED_COLLECTION_ID_FIRST(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    AUTHORIZED_COLLECTION_ID_LAST(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buildAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[AttestationStructOutput[]]>;

    deleteAttestations(
      collectionIds: BigNumberish[],
      attestationsOwner: string,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    generateAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAttestationRegistry(overrides?: CallOverrides): Promise<[string]>;

    getAvailableRootsRegistry(overrides?: CallOverrides): Promise<[string]>;

    getCommitmentMapperRegistry(overrides?: CallOverrides): Promise<[string]>;

    getDestinationOfNullifier(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getNullifierFromExtraData(
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVerifier(overrides?: CallOverrides): Promise<[string]>;
  };

  AUTHORIZED_COLLECTION_ID_FIRST(overrides?: CallOverrides): Promise<BigNumber>;

  AUTHORIZED_COLLECTION_ID_LAST(overrides?: CallOverrides): Promise<BigNumber>;

  buildAttestations(
    request: RequestStruct,
    proofData: BytesLike,
    overrides?: CallOverrides
  ): Promise<AttestationStructOutput[]>;

  deleteAttestations(
    collectionIds: BigNumberish[],
    attestationsOwner: string,
    proofData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  generateAttestations(
    request: RequestStruct,
    proofData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAttestationRegistry(overrides?: CallOverrides): Promise<string>;

  getAvailableRootsRegistry(overrides?: CallOverrides): Promise<string>;

  getCommitmentMapperRegistry(overrides?: CallOverrides): Promise<string>;

  getDestinationOfNullifier(
    nullifier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getNullifierFromExtraData(
    extraData: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVerifier(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    AUTHORIZED_COLLECTION_ID_FIRST(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    AUTHORIZED_COLLECTION_ID_LAST(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buildAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<AttestationStructOutput[]>;

    deleteAttestations(
      collectionIds: BigNumberish[],
      attestationsOwner: string,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<AttestationStructOutput[]>;

    generateAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<AttestationStructOutput[]>;

    getAttestationRegistry(overrides?: CallOverrides): Promise<string>;

    getAvailableRootsRegistry(overrides?: CallOverrides): Promise<string>;

    getCommitmentMapperRegistry(overrides?: CallOverrides): Promise<string>;

    getDestinationOfNullifier(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getNullifierFromExtraData(
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVerifier(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AttestationDeleted(tuple)"(
      attestation?: null
    ): AttestationDeletedEventFilter;
    AttestationDeleted(attestation?: null): AttestationDeletedEventFilter;

    "AttestationGenerated(tuple)"(
      attestation?: null
    ): AttestationGeneratedEventFilter;
    AttestationGenerated(attestation?: null): AttestationGeneratedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NullifierDestinationUpdated(uint256,address)"(
      nullifier?: null,
      newOwner?: null
    ): NullifierDestinationUpdatedEventFilter;
    NullifierDestinationUpdated(
      nullifier?: null,
      newOwner?: null
    ): NullifierDestinationUpdatedEventFilter;
  };

  estimateGas: {
    AUTHORIZED_COLLECTION_ID_FIRST(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    AUTHORIZED_COLLECTION_ID_LAST(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buildAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deleteAttestations(
      collectionIds: BigNumberish[],
      attestationsOwner: string,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    generateAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAttestationRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getAvailableRootsRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getCommitmentMapperRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getDestinationOfNullifier(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNullifierFromExtraData(
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVerifier(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    AUTHORIZED_COLLECTION_ID_FIRST(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    AUTHORIZED_COLLECTION_ID_LAST(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buildAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deleteAttestations(
      collectionIds: BigNumberish[],
      attestationsOwner: string,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    generateAttestations(
      request: RequestStruct,
      proofData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAttestationRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAvailableRootsRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCommitmentMapperRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDestinationOfNullifier(
      nullifier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNullifierFromExtraData(
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
