export type IconProps = {
  style?: React.CSSProperties;
  name:
    | "arrowLeft-outline-white"
    | "logoTwitter-fill-gradient"
    | "logoTwitter-fill-white"
    | "logoTwitter-fill-white-2"
    | "logoGithub-fill-gradient"
    | "logoGithub-fill-white"
    | "logoDiscord-fill-gradient"
    | "logoDiscord-fill-white"
    | "logoDiscord-fill-primary"
    | "logoSismo-outline-white"
    | "cross-outline-white"
    | "logoEth-outline-primary"
    | "logoTwitter-fill-primary"
    | "logoGithub-fill-primary"
    | "logoDiscord-fill-blue"
    | "arrowDown-outline-lightBlue"
    | "badge-fill-lightBlue"
    | "badge-fill-blue4"
    | "settings-outline-lightBlue"
    | "confirmNotif-outline-blue"
    | "cross-outline-blue"
    | "logoEthereum-fill-green"
    | "logoEthereum-fill-lightBlue"
    | "logoEthereum-fill-blue0"
    | "logoEthereum-fill-blue3"
    | "logoPolygon-fill-green"
    | "logoPolygon-fill-white"
    | "logoPolygon-fill-blue0"
    | "logoPolygon-fill-blue3"
    | "logoAvalanche-fill-green"
    | "logoAvalanche-fill-white"
    | "logoGnosis-fill-green"
    | "logoGnosis-fill-white"
    | "logoTelegram-fill-white"
    | "logoTwitter-fill-white"
    | "logoTwitter-fill-blue0"
    | "logoTwitter-rounded-blue0"
    | "logoGithub-fill-white"
    | "logoGithub-fill-blue0"
    | "logoDiscord-fill-white"
    | "check-outline-blue"
    | "info-outline-lightblue"
    | "gear-outline-blue"
    | "back-outline-lightBlue"
    | "externalLink-outline-white"
    | "key-outline-green"
    | "key-outline-white"
    | "key-outline-lightBlue"
    | "plus-outline-white"
    | "check-outline-white"
    | "check-outline-green"
    | "warning-outline-orange"
    | "edit-outline-blue"
    | "switch-outline-white"
    | "key-fill-blue"
    | "switch-outline-blue"
    | "smallArrowLeft-outline-white"
    | "question-outline-white"
    | "question-outline-lightBlue"
    | "plus-outline-blue"
    | "logoSnapshot-fill-blue"
    | "logoOpensea-fill-color"
    | "arrowDown-outline-white"
    | "playground-outline-green"
    | "playground-outline-blue"
    | "sismo-outline-white"
    | "logoEtherscan-fill-white"
    | "logoPolygon-fill-color"
    | "arrowDown-outline-grey"
    | "eligibleAccounts-outline-white"
    | "logoEthereum-fill-color"
    | "testnet-outline-blue"
    | "testnet-outline-orange"
    | "vault-outline-white"
    | "vault-outline-blue0"
    | "sources-outline-white"
    | "destinations-outline-white"
    | "settings-outline-white"
    | "delete-outline-white"
    | "edit-outline-white"
    | "copy-outline-white"
    | "badge-outline-white"
    | "badge-outline-blue8"
    | "logoEthereum-fill-bluem05"
    | "logoTelegram-fill-bluem05"
    | "logoTwitter-fill-bluem05"
    | "logoGithub-fill-bluem05"
    | "more-outline-white"
    | "lock-outline-white"
    | "arrowRight-outline-lightBlue"
    | "more-outline-blue2"
    | "key-outline-blue";
};

const IconExtention = {};

//[description camelCase] - [outline|fill] - [color]

export default function Icon({ style, name }: IconProps): JSX.Element {
  return (
    <img
      src={`/icons/${name}.${IconExtention[name] || "svg"}`}
      style={style}
      alt={name}
    />
  );
}
