name: Deploy Staging Beta environment
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Staging Beta
    runs-on: ubuntu-latest
    environment:
      name: staging-beta
      url: https://staging.vault-beta.sismo.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          static-bucket-name: staging.vault-beta.sismo.io
          env: staging-beta
          sentry-env: STAGING_BETA
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ secrets.SENTRY_ORG }}
          sentry-project: ${{ secrets.SENTRY_PROJECT }}
