name: Deploy Playground environment
on:
  workflow_dispatch: {}
  push:
    tags:
      - playground*

jobs:
  deploy:
    name: Deploy Playground
    runs-on: ubuntu-latest
    environment:
      name: playground
      url: https://playground.sismo.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          static-bucket-name: playground.sismo.io
          env: playground
          sentry-env: PLAYGROUND
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ secrets.SENTRY_ORG }}
          sentry-project: ${{ secrets.SENTRY_PROJECT }}
