name: Deploy Prod Beta environment
on:
  workflow_dispatch: {}


jobs:
  deploy:
    name: Deploy Prod Beta
    runs-on: ubuntu-latest
    environment:
      name: prod-beta
      url: https://vault-beta.sismo.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          static-bucket-name: vault-beta.sismo.io
          env: prod-beta
