name: Deploy Testnet Private (zikies) environment
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Testnet Private
    runs-on: ubuntu-latest
    environment:
      name: testnet-private-beta
      url: https://vault-beta.zikies.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          static-bucket-name: vault-beta.zikies.io
          npm-token: ${{ secrets.NPM_TOKEN }}
          env: testnet-private-beta
          sentry-env: TESTNETS_PRIVATE_BETA
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ secrets.SENTRY_ORG }}
          sentry-project: ${{ secrets.SENTRY_PROJECT }}
